MAIN_DIR = "D:\python project\data\proteins"

NUM_SAMPLES_IN_DATAFRAME = 10000

AMINO_ACIDS = 'ACDEFGHIKLMNPQRSTVWY'
NON_STANDARD_AMINO_ACIDS = "UZX"
AMINO_ACID_TO_INDEX = {aa: i + 1 for i, aa in enumerate(AMINO_ACIDS)}  # 1-indexed for padding

MIN_SIZE = 10
MAX_TRAINING_SIZE = 150
MAX_SIZE = 750

DECAY_RATE = 0.25
